Repository reddit/baseplate.py, pull requests merged in 2024-04, with the labels that each got.

#838 Bump MarkupSafe and Jinja2
  requirements-transitive.txt
  requirements.txt
Labels: dependencies, v2.7

#805 Update Thift Pool metrics to use class qualname
  baseplate/clients/thrift.py
  tests/unit/clients/thrift_tests.py
Labels: v2.7

#871 Bump moto from 4.2.13 to 5.0.5
  requirements-transitive.txt
  tests/unit/sidecars/live_data_watcher_loader_tests.py
  tests/unit/sidecars/live_data_watcher_tests.py
Labels: dependencies

#851 Update Sphinx
  requirements-transitive.txt
  requirements.txt
Labels: dependencies

#895 Do not use deprecated utcnow in ipython log line:
  baseplate/server/__init__.py
Labels: v2.7

#894 Use Self type in _BaseKafkaQueueConsumerFactory.new()
  baseplate/frameworks/queue_consumer/kafka.py
  poetry.lock
  pyproject.toml
Labels: v2.7

#833 Raise a `SlotNotCoveredError` in rediscluster if slot doesnt exist
  baseplate/clients/redis_cluster.py
Labels: v2.7

#785 feat: Improve shutdown Delay default
  baseplate/server/__init__.py
Labels: v2.7
